#!/usr/bin/env python3
"""Generate the per-face cover-identity app icons (decisions §9a).

Run from the repo root:

    python3 tools/generate_cover_icons.py

Writes, in place:
    android/app/src/main/res/drawable/ic_launcher_notepad_foreground.xml
    android/app/src/main/res/drawable/ic_launcher_gallery_foreground.xml
    ios/SafeBox/Support/Assets.xcassets/AppIconNotepad.appiconset/AppIconNotepad.png
    ios/SafeBox/Support/Assets.xcassets/AppIconGallery.appiconset/AppIconGallery.png

WHY THIS EXISTS. §9a promises the two platforms' artwork "cannot drift" because
it is authored once and emitted twice. That guarantee is only real if the
emitting actually happens here: hand-editing either the Android vector or the
iOS PNG breaks it silently, because nothing else re-derives one from the other.
Edit the shape tables below and re-run; never touch the generated files.

Shapes are authored in the Android adaptive-icon 108x108 space and emitted as
an Android <vector> foreground (the adaptive icon supplies the background) and
as a 1024x1024 iOS PNG with the background painted in.

SAFE ZONE. Adaptive icons guarantee only the central 72x72 (y/x 18..90); a
circular mask crops to r=36 about (54,54). Corners of a rounded rect reaching
past that circle are normal and are house style here (the shipped calculator's
worst corner is r=46). What must NOT happen is an edge crossing y=90: that
crops a shape's silhouette rather than its corner, and a visibly cropped decoy
icon is itself a small tell. `python3 tools/generate_cover_icons.py --check`
asserts it.

Requires rsvg-convert (brew install librsvg).
"""
import argparse
import math
import subprocess
import sys
import tempfile
from pathlib import Path

BG = "#17191C"
SLATE = "#2A2D33"
KEY = "#43484F"
LIGHT = "#F5F6F7"
AMBER = "#B45309"

VIEWPORT = 108
IOS_PX = 1024
SCALE = IOS_PX / VIEWPORT
SAFE_MIN, SAFE_MAX = 18, 90


def rrect(x, y, w, h, r):
    """Rounded rect, written with the h/v/a segments the existing calculator
    drawable uses so the generated files read like the hand-written one."""
    return (
        f"M{x + r},{y} h{w - 2 * r} a{r},{r} 0 0 1 {r},{r} "
        f"v{h - 2 * r} a{r},{r} 0 0 1 -{r},{r} "
        f"h-{w - 2 * r} a{r},{r} 0 0 1 -{r},-{r} "
        f"v-{h - 2 * r} a{r},{r} 0 0 1 {r},-{r} z"
    )


def top_band(x, y, w, h, r):
    """A band across the top of a rounded rect: rounded above, square below."""
    return (
        f"M{x + r},{y} h{w - 2 * r} a{r},{r} 0 0 1 {r},{r} "
        f"v{h - r} h-{w} v-{h - r} a{r},{r} 0 0 1 {r},-{r} z"
    )


def notepad():
    """Cover identity for the PIN pad face: a ruled page with an amber binding.

    Everything derives from the page rect, so the band and rules cannot drift
    out of it — the bug that shipped the first time was a hand-placed rule
    sitting below a hand-placed page.
    """
    # 24..84: optically centred on the viewport's 54 midline (the first cut
    # sat at 22..94, 4dp past the safe zone and 4dp low), and still taller than
    # the landscape gallery frame, which suits a portrait page.
    px, py, pw, ph, r = 31, 24, 46, 60, 6
    band_h = 12
    rule_x, rule_w, rule_h = px + 8, 30, 4.5
    # Four evenly spaced rules between the band and the page's bottom padding.
    top = py + band_h
    slots = 4
    gap = (ph - band_h - slots * rule_h) / (slots + 1)
    ys = [top + gap * (i + 1) + rule_h * i for i in range(slots)]
    return [
        (SLATE, rrect(px, py, pw, ph, r)),
        (AMBER, top_band(px, py, pw, band_h, r)),
        (LIGHT, rrect(rule_x, round(ys[0], 1), rule_w, rule_h, rule_h / 2)),
        (LIGHT, rrect(rule_x, round(ys[1], 1), rule_w, rule_h, rule_h / 2)),
        (LIGHT, rrect(rule_x, round(ys[2], 1), rule_w, rule_h, rule_h / 2)),
        # A short, dimmer last line: the page reads as part-written, not blank.
        (KEY, rrect(rule_x, round(ys[3], 1), 17, rule_h, rule_h / 2)),
    ]


def gallery():
    """Cover identity for the pattern face: a framed photo, sun over a ridge."""
    return [
        (SLATE, rrect(24, 26, 60, 56, 7)),
        (AMBER, "M42,46 m-6.5,0 a6.5,6.5 0 1 0 13,0 a6.5,6.5 0 1 0 -13,0 z"),
        (LIGHT, "M30,75 L46,55 L57,67 L66,56 L78,75 z"),
    ]


ICONS = {
    "notepad": ("AppIconNotepad", notepad),
    "gallery": ("AppIconGallery", gallery),
}


def android_vector(paths):
    body = "\n".join(
        f'    <path\n        android:fillColor="{c}"\n        android:pathData="{d}" />'
        for c, d in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- GENERATED by tools/generate_cover_icons.py - do not hand-edit.\n"
        "     Original artwork, deliberately imitating no vendor's icon.\n"
        "     See docs/plans/iteration-3-decisions.md section 9a. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        f"{body}\n"
        "</vector>\n"
    )


def ios_svg(paths):
    body = "\n".join(f'    <path fill="{c}" d="{d}"/>' for c, d in paths)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{IOS_PX}" '
        f'height="{IOS_PX}" viewBox="0 0 {IOS_PX} {IOS_PX}">\n'
        f'  <rect width="{IOS_PX}" height="{IOS_PX}" fill="{BG}"/>\n'
        f'  <g transform="scale({SCALE})">\n{body}\n  </g>\n'
        "</svg>\n"
    )


def extents(paths, tmp):
    """Y-extent of the drawn shapes, in 108-space, measured from a real render.

    Parsing the path data would be wrong: these paths are mostly relative
    (h/v/a) segments, so the only absolute y in a rounded rect is its top edge
    and a naive parser silently reports a shape as ending where it starts. The
    rendered pixels are the ground truth, so rasterise and measure those.
    """
    from PIL import Image

    svg = tmp / "measure.svg"
    png = tmp / "measure.png"
    # Render the shapes alone, no background, so alpha marks exactly the art.
    body = "\n".join(f'    <path fill="{c}" d="{d}"/>' for c, d in paths)
    svg.write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{VIEWPORT}" '
        f'height="{VIEWPORT}" viewBox="0 0 {VIEWPORT} {VIEWPORT}">\n{body}\n</svg>\n'
    )
    subprocess.run(
        ["rsvg-convert", "-w", str(VIEWPORT), "-h", str(VIEWPORT), str(svg), "-o", str(png)],
        check=True,
    )
    box = Image.open(png).getchannel("A").getbbox()
    svg.unlink()
    png.unlink()
    if box is None:
        return math.inf, -math.inf
    return float(box[1]), float(box[3])


def check(tmp):
    bad = False
    for name, (_, build) in ICONS.items():
        lo, hi = extents(build(), tmp)
        ok = hi <= SAFE_MAX
        centre = (lo + hi) / 2
        print(
            f"{name:<9} y {lo:5.1f}..{hi:5.1f}  centre {centre:5.1f}  "
            f"safe<={SAFE_MAX}  {'ok' if ok else 'PAST SAFE ZONE'}"
        )
        bad |= not ok
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify the safe zone, write nothing")
    ap.add_argument("--root", default=".", help="repo root")
    args = ap.parse_args()
    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            sys.exit(check(Path(tmp)))

    root = Path(args.root).resolve()
    drawable = root / "android/app/src/main/res/drawable"
    assets = root / "ios/SafeBox/Support/Assets.xcassets"
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        for name, (ios_name, build) in ICONS.items():
            paths = build()
            lo, hi = extents(paths, tmp)
            if hi > SAFE_MAX:
                sys.exit(f"{name}: y reaches {hi}, past the {SAFE_MAX} safe zone")
            (drawable / f"ic_launcher_{name}_foreground.xml").write_text(android_vector(paths))
            svg = tmp / f"{name}.svg"
            svg.write_text(ios_svg(paths))
            png = assets / f"{ios_name}.appiconset" / f"{ios_name}.png"
            subprocess.run(
                ["rsvg-convert", "-w", str(IOS_PX), "-h", str(IOS_PX), str(svg), "-o", str(png)],
                check=True,
            )
            print(f"{name}: vector + {png.name}  (y {lo:.1f}..{hi:.1f}, centre {(lo + hi) / 2:.1f})")


if __name__ == "__main__":
    main()
