import Foundation
import ImageIO
import Testing
import UIKit
import UniformTypeIdentifiers
@testable import SafeBox

/// N3 — video import, storage and deletion. The fixture is a real `.mov`
/// generated by `TestVideo` with `AVAssetWriter`, so `AVURLAsset` /
/// `AVAssetImageGenerator` are genuinely exercised (no faked probe, no binary
/// checked into the repo).
@MainActor
struct VideoImportTests {
    private func makeStack() -> (SwiftDataPhotoRepository, PhotoFileStore, URL) {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("SafeBoxVideoTests-\(UUID().uuidString)", isDirectory: true)
        let fileStore = PhotoFileStore(rootURL: root)
        let repo = SwiftDataPhotoRepository(container: ModelContainerFactory.inMemory(),
                                            fileStore: fileStore)
        return (repo, fileStore, root)
    }

    private func fileExists(_ url: URL) -> Bool {
        FileManager.default.fileExists(atPath: url.path)
    }

    /// Generates the fixture and copies it into the store's own `Staging/`
    /// directory — exactly where `StagedVideo` puts a picked file — returning
    /// the staged URL and the original bytes.
    private func stageFixture(_ fileStore: PhotoFileStore, in root: URL,
                              frameCount: Int = 30) async throws -> (staged: URL, bytes: Data) {
        let source = root.appendingPathComponent("fixture-\(UUID().uuidString).mov")
        try await TestVideo.write(to: source, frameCount: frameCount)
        let bytes = try Data(contentsOf: source)
        let staged = try VaultStaging.stage(source, in: fileStore.stagingURL)
        return (staged, bytes)
    }

    // MARK: - Import

    @Test func videoImportStoresOriginalBytesPosterThumbnailAndDuration() async throws {
        let (_, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let fixture = try await stageFixture(fileStore, in: root) // 30 frames @ 30 fps = 1.0 s

        let stored = try await fileStore.store(videoAt: fixture.staged)

        #expect(stored.mediaType == MediaType.video.rawValue)
        #expect(stored.fileName.hasSuffix(".mov"))       // real extension, no re-container
        #expect(stored.mimeType == "video/quicktime")
        #expect(stored.width == 160)
        #expect(stored.height == 120)
        #expect(stored.byteCount == fixture.bytes.count)

        let durationMs = try #require(stored.durationMs)
        #expect(durationMs >= 900 && durationMs <= 1100)
        #expect(MediaMetadataFormatter.duration(milliseconds: durationMs) == "0:01")

        // Byte-for-byte original: no re-encode, no transcode.
        let written = try Data(contentsOf: fileStore.photoURL(fileName: stored.fileName))
        #expect(written == fixture.bytes)
        // The staged copy is consumed by the move — nothing lingers in Staging/.
        #expect(!fileExists(fixture.staged))

        // Poster thumbnail, written exactly like a photo's.
        let thumbURL = fileStore.thumbnailURL(thumbFileName: stored.thumbFileName)
        #expect(stored.thumbFileName.hasSuffix(".jpg"))
        #expect(fileExists(thumbURL))
        let source = try #require(CGImageSourceCreateWithURL(thumbURL as CFURL, nil))
        #expect((CGImageSourceGetType(source) as String?) == UTType.jpeg.identifier)
        let thumb = try #require(UIImage(contentsOfFile: thumbURL.path))
        #expect(thumb.size.width > 0 && thumb.size.height > 0)
        #expect(max(thumb.size.width, thumb.size.height) <= PhotoFileStore.thumbnailMaxPixel)
    }

    @Test func importedVideoRowCarriesMediaTypeAndDuration() async throws {
        let (repo, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let album = try repo.createAlbum(name: "A")
        let fixture = try await stageFixture(fileStore, in: root)
        let stored = try await fileStore.store(videoAt: fixture.staged)

        let photo = try #require(try repo.insertPhoto(stored, albumId: album.id))
        #expect(photo.isVideo)
        #expect(photo.mediaType == MediaType.video.rawValue)
        #expect(photo.durationMs == stored.durationMs)
        // Re-fetched through the live query, the way the grid sees it.
        let fetched = try #require(repo.photos(in: album).first)
        #expect(fetched.isVideo)
        #expect(fetched.durationMs == stored.durationMs)
    }

    @Test func failedVideoImportLeavesNoStagedFileRowOrThumbnail() async throws {
        let (_, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        // A file with a movie extension that is not a movie.
        let staged = fileStore.stagingURL.appendingPathComponent("broken.mov")
        try FileManager.default.createDirectory(at: fileStore.stagingURL, withIntermediateDirectories: true)
        try Data("not a movie".utf8).write(to: staged)

        await #expect(throws: (any Error).self) {
            _ = try await fileStore.store(videoAt: staged)
        }
        // The staged bytes are always consumed, success or failure.
        #expect(!fileExists(staged))
        let photos = (try? FileManager.default.contentsOfDirectory(atPath: fileStore.photosURL.path)) ?? []
        #expect(photos.isEmpty)
    }

    /// The image path is unchanged by N3: non-image bytes still throw
    /// `unreadableImage` rather than being filed away as a video.
    @Test func storingNonImageDataStillThrowsUnreadableImage() async throws {
        let (_, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let source = root.appendingPathComponent("fixture.mov")
        try await TestVideo.write(to: source, frameCount: 6)
        let movieBytes = try Data(contentsOf: source)

        await #expect(throws: PhotoFileStore.StoreError.unreadableImage) {
            _ = try await fileStore.store(data: movieBytes)
        }
        await #expect(throws: PhotoFileStore.StoreError.unreadableImage) {
            _ = try await fileStore.store(data: Data("nonsense".utf8))
        }
    }

    // MARK: - Mixed albums

    @Test func mixedPhotoAndVideoAlbumListsAndOrdersByImportOrder() async throws {
        let (repo, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let album = try repo.createAlbum(name: "Mixed")

        let first = try #require(try repo.insertPhoto(try await fileStore.store(data: TestPNG.data()),
                                                      albumId: album.id))
        let video = try #require(try repo.insertPhoto(
            try await fileStore.store(videoAt: try await stageFixture(fileStore, in: root, frameCount: 15).staged),
            albumId: album.id))
        let third = try #require(try repo.insertPhoto(try await fileStore.store(data: TestPNG.data()),
                                                      albumId: album.id))

        // Ordering is mediaType-agnostic: plain import order (`sortIndex`).
        let indexes: [Int] = [first.sortIndex, video.sortIndex, third.sortIndex]
        #expect(indexes == [0, 1, 2])
        let listed = repo.photos(in: album)
        #expect(listed.map(\.id) == [first.id, video.id, third.id])
        #expect(listed.map(\.isVideo) == [false, true, false])
        // The video's duration survived the round-trip through the row.
        let storedDuration = try #require(listed[1].durationMs)
        #expect(storedDuration >= 400 && storedDuration <= 600) // 15 frames @ 30 fps
        // Sorting an album by photo count counts videos like anything else.
        #expect(repo.albums(sortedBy: .photoCount).first?.id == album.id)
    }

    // MARK: - Deletion

    @Test func purgingAVideoRemovesTheOriginalAndItsPoster() async throws {
        let (repo, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let album = try repo.createAlbum(name: "A")
        let stored = try await fileStore.store(videoAt: try await stageFixture(fileStore, in: root).staged)
        let video = try #require(try repo.insertPhoto(stored, albumId: album.id))
        let fileURL = fileStore.photoURL(fileName: video.fileName)
        let thumbURL = fileStore.thumbnailURL(thumbFileName: video.thumbFileName)

        // Soft delete keeps both files (P3), exactly like a photo.
        try repo.deletePhotos([video])
        #expect(repo.photos(in: album).isEmpty)
        #expect(repo.trashedPhotos().map(\.id) == [video.id])
        #expect(fileExists(fileURL))
        #expect(fileExists(thumbURL))

        // Purge removes the row AND both files.
        try await repo.purgePhotos(ids: [video.id])
        #expect(repo.trashedPhotos().isEmpty)
        #expect(!fileExists(fileURL))
        #expect(!fileExists(thumbURL))
    }

    @Test func orphanSweepSparesAVideoBelongingToATrashedRow() async throws {
        let (repo, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let album = try repo.createAlbum(name: "A")
        let stored = try await fileStore.store(videoAt: try await stageFixture(fileStore, in: root).staged)
        let video = try #require(try repo.insertPhoto(stored, albumId: album.id))
        try repo.deletePhotos([video])

        await repo.performOrphanSweep()

        #expect(fileExists(fileStore.photoURL(fileName: video.fileName)))
        #expect(fileExists(fileStore.thumbnailURL(thumbFileName: video.thumbFileName)))
    }

    // MARK: - Details sheet (N2 forwarding)

    @Test func detailsSheetShowsDurationForVideosAndNotForPhotos() async throws {
        let (repo, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let album = try repo.createAlbum(name: "A")
        let still = try #require(try repo.insertPhoto(try await fileStore.store(data: TestPNG.data()),
                                                      albumId: album.id))
        let video = try #require(try repo.insertPhoto(
            try await fileStore.store(videoAt: try await stageFixture(fileStore, in: root).staged),
            albumId: album.id))

        let stillRows = PhotoMetadata(photo: still).rows(locale: Locale(identifier: "en_US"))
        #expect(stillRows.count == 4)
        #expect(!stillRows.contains { $0.label == VaultCopy.photoInfoDuration })

        let videoRows = PhotoMetadata(photo: video).rows(locale: Locale(identifier: "en_US"))
        #expect(videoRows.count == 5)
        // Decisions §8: Duration sits after Type and before Imported.
        #expect(videoRows.map(\.label) == [
            VaultCopy.photoInfoDimensions, VaultCopy.photoInfoSize, VaultCopy.photoInfoType,
            VaultCopy.photoInfoDuration, VaultCopy.photoInfoImported,
        ])
        #expect(videoRows[2].value == "MOV")
        #expect(videoRows[3].value == "0:01")   // the 1.0 s fixture
        #expect(videoRows[0].value == "160 × 120")
    }

    // MARK: - Staging

    @Test func stagingLivesInsideTheVaultAndIsClearedAtLaunch() async throws {
        let (_, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }

        // Staging always hangs off the store's own root…
        #expect(fileStore.stagingURL.path.hasPrefix(root.path))
        #expect(fileStore.stagingURL.lastPathComponent == VaultStaging.directoryName)
        // …and in the live app that root is the vault directory, never the
        // system tmp dir, which `cleanTemporaryDirectory()` wipes on every
        // lock — that would delete an import still in flight.
        let live = VaultStaging.liveDirectoryURL()
        #expect(live.path.hasPrefix(ModelContainerFactory.vaultDirectoryURL().path))
        #expect(!live.path.hasPrefix(FileManager.default.temporaryDirectory.path))

        let fixture = try await stageFixture(fileStore, in: root, frameCount: 6)
        #expect(fileExists(fixture.staged))
        #expect(fixture.staged.pathExtension == "mov")   // real extension kept
        #expect(try Data(contentsOf: fixture.staged) == fixture.bytes)

        await fileStore.cleanStagingDirectory()
        #expect(!fileExists(fixture.staged))
        #expect(!fileExists(fileStore.stagingURL))
    }

    /// The `Transferable` closure is static, so it asks `VaultStaging` where to
    /// stage. The importer declares its own store's directory, otherwise a
    /// preview/test container would write picked bytes into the REAL vault.
    @Test func theImporterStagesIntoTheStoreThatOwnsIt() async throws {
        let (repo, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        defer { VaultStaging.setDestinationDirectory(nil) }

        // With nothing declared, staging falls back to the live vault — which
        // is exactly what `AppContainer.live()` gets.
        VaultStaging.setDestinationDirectory(nil)
        #expect(VaultStaging.destinationDirectoryURL() == VaultStaging.liveDirectoryURL())

        let importer = PhotoImporter(fileStore: fileStore, repository: repo)
        _ = await importer.importItems([], albumId: UUID())
        #expect(VaultStaging.destinationDirectoryURL() == fileStore.stagingURL)

        // And a staged file really does land under that store's root.
        let source = root.appendingPathComponent("fixture-\(UUID().uuidString).mov")
        try await TestVideo.write(to: source, frameCount: 6)
        let staged = try VaultStaging.stageCurrent(source)
        #expect(staged.path.hasPrefix(fileStore.stagingURL.path))
        #expect(!staged.path.hasPrefix(VaultStaging.liveDirectoryURL().path))
    }

    @Test func eraseEverythingRemovesStagedBytesToo() async throws {
        let (_, fileStore, root) = makeStack()
        defer { try? FileManager.default.removeItem(at: root) }
        let fixture = try await stageFixture(fileStore, in: root, frameCount: 6)

        await fileStore.deleteAll()

        #expect(!fileExists(fixture.staged))
        #expect(!fileExists(fileStore.stagingURL))
    }
}
